; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_custom]
platform = espressif32 @ 6.13.0
board = esp32-s3-devkitc-1
framework = espidf

upload_speed = 921600 ; Upload baud rate
board_upload.flash_size = 16MB ; Flash size

board_build.partitions = partitions.csv ; Partition table

; Enable compilation flags for OPI support (required in some versions)
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_MODE_OCT=1
