; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_custom]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

upload_speed = 921600 ; 设置烧录波特率 S3支持高速下载
board_upload.flash_size = 16MB ; Flash 识别和烧录大小

board_build.partitions = partitions.csv ; 设置分区表

; 开启OPI支持的编译标志 (部分版本需要)
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_MODE_OCT=1
